### ISSUE TITLE
EPIC: Refactor code base

### ISSUE THREAD

**Issue by johnlees** [johnlees/PopPUNK#103]
Things to be done off the top of my head:

- [ ] Rewrite the sketchlib interface from scratch, the current one is based around mash
- [ ] Remove all `use_mash` instances, and the partial functions
- [ ] Redo command line options (#73)
- [ ] Move visualisations out (#77)
- [ ] Integrate lineage assignment with sketchlib functions and model objects (#79)
- [ ] Rewrite the documentation, probably from scratch (#74)
- [ ] Make a simpler `assign_query` API

**Comment by nickjcroucher** [comment]
Happy to take on removal of mash/partial functions, moving visualisation code and test updates - they seem to need your expertise least?

**Comment by johnlees** [comment]
I became increasingly aware with the latest changes that a lot of parts of the code now are not as we would write them if doing this with our current tools. I think the models are broadly ok, but the sketching, distances, networks and visualisations have all changed a lot since the first version. I think all of `__main__` could basically do with a comb through at some point, although it doesn't have to be right now.

I'm happy with whatever you'd like to do! 

- Removing use_mash/partials would be a prerequisite for the first point.
- With the tests at least checking the cluster results are the same each time would be a start.
- I should probably do #73, #74 and #79, at least.
